[X] ROOT "/" -> improve desgig
[X] LOGIN  -> DESIGN
[X] DASHBOARD (LOGGED) -> LOGOUT BUTTON TO END SESSION
[X] REGISTER UI DESIGN
[x] PREDICTIONS "/random-forest" RANDOM FOREST (ERROR FIX)
[] UPLAOD 5 MODELS (PKL AND OTHER STRUCTURE) AND RUN
[] PYTHON API NEW STRUCTURE
[] 5 MODELV ROUTE TO PREDICT
[] PREDICTIONS DESIGN IMPROVE (WITH MODALS OR HOVER INFO SOMETHING GOOD)
[] MODELS PREDICTION (SET SPECIFIC INTERVAL, SHOW PLOTS LIKE SCATTER,  SHOW FUTURE WITH "REAL DATA"??)
[] MANAGE USERS (SHOW USERS [ROL?] AND WHY ERROR)
[] CREATE USERS (IMPROVE DESIGN AND FUNCTIONALITY)
[] MANAGE MODELS & MANAGE USERS DESIGN
[] CREATE MODELS DESIGN
[] EDIT AND DELETE (USERS AND MODELS)

[] END SESSION IN TEH FLOW OF PREDICTIONS IN THE NAVBAR
[] NAVBAR WITH SESSIONS
[] ANCACHURO INFO AND SOO

(
    * 17-07 MEJORAR EL DASHBOARD LA PRESENTACION 
    * USERS CRUD ["SERVICE, CONTROLLER AND FRONTEND"] 
    * USERS ROLES TO SEE WHICH ARE REGISTERED
    * CRUD MODELS???   
)
50 SEGUNDOS TO UP DE BACKEND SERVER AT LEAST