[] RAIZ "/" -> improve desgig
[] LOGIN  -> DESIGN
[] DASHBOARD (LOGGED) -> LOGOUT BUTTON TO END SESSION
[] END SESSION IN TEH FLOW OF PREDICTIONS IN THE NAVBAR
[] MANAGE USERS (SHOW USERS [ROL?] AND WHY ERROR)
[] CREATE USERS (IMPROVE DESIGN AND FUNCTIONALITY)
[] MANAGE MODELS & MANAGE USERS DESIGN
[] CREATE MODELS DESIGN
[] EDIT AND DELETE (USERS AND MODELS)
[] PREDICTIONS "/random-forest" RANDOM FOREST (ERROR FIX)
[] UPLAOD 5 MODELS
[] PREDICTIONS DESIGN IMPROVE (WITH MODALS OR HOVER INFO SOMETHING GOOD)
[] MODELS PREDICTION (SET SPECIFIC INTERVAL, SHOW PLOTS LIKE SCATTER,  SHOW FUTURE WITH "REAL DATA"??)

[] ANCACHURO INFO AND SOO